book/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    path('', views.Book.as_view(), name='book'),
    path('bookController/', views.BookController.as_view(), name='bookController'),
    path('authorForm/', views.AuthorFormView.as_view(), name='authorForm'),
    path('updateAuthorForm/<int:id>', views.AuthorFormUpdateView.as_view(), name='authorFormUpdate'),
    path('deleteAuthorForm/<int:id>', views.AuthorFormDeleteView.as_view(), name='authorFormDelete'),
    path('categoryForm/', views.CategoryFormView.as_view(), name='categoryForm'),
    path('updateCategoryForm/<int:id>', views.CategoryFormUpdateView.as_view(), name='categoryFormUpdate'),
    path('deleteCategoryForm/<int:id>', views.CategoryFormDeleteView.as_view(), name='categoryFormDelete'),
    path('publisherForm/', views.PublisherFormView.as_view(), name='publisherForm'),
    path('updatePublisherForm/<int:id>', views.PublisherFormUpdateView.as_view(), name='publisherFormUpdate'),
    path('deletePublisherForm/<int:id>', views.PublisherFormDeleteView.as_view(), name='publisherFormDelete'),
    path('bookForm/', views.BookFormView.as_view(), name='bookForm'),
    path('updateBookForm/<int:id>', views.BookFormUpdateView.as_view(), name='bookFormUpdate'),
    path('deleteBookForm/<int:id>', views.BookFormDeleteView.as_view(), name='bookFormDelete'),
    path('bookItemForm/', views.BookItemFormView.as_view(), name='bookItemForm'),
    path('updateBookItemForm/<int:id>', views.BookItemFormUpdateView.as_view(), name='bookItemFormUpdate'),
    path('deleteBookItemForm/<int:id>', views.BookItemFormDeleteView.as_view(), name='bookItemFormDelete'),
]

clothes/urls.py
from django.urls import path
from . import views

app_name = 'clothes'
urlpatterns = [
    path('', views.ClothesABC.as_view(), name='clothes'),
    path('clothesController/', views.ClothesController.as_view(), name='clothesController'),
    path('typeClothesForm/', views.TypeClothesFormView.as_view(), name='typeClothesForm'),
    path('updateTypeClothesForm/<int:id>', views.TypeClothesFormUpdateView.as_view(), name='typeClothesFormUpdate'),
    path('deleteTypeClothesForm/<int:id>', views.TypeClothesFormDeleteView.as_view(), name='typeClothesFormDelete'),
    path('brandClothesForm/', views.BrandClothesFormView.as_view(), name='brandClothesForm'),
    path('updateBrandClothesForm/<int:id>', views.BrandClothesFormUpdateView.as_view(), name='brandClothesFormUpdate'),
    path('deleteBrandClothesForm/<int:id>', views.BrandClothesFormDeleteView.as_view(), name='brandClothesFormDelete'),
    path('clothesForm/', views.ClothesFormView.as_view(), name='clothesForm'),
    path('updateClothesForm/<int:id>', views.ClothesFormUpdateView.as_view(), name='clothesFormUpdate'),
    path('deleteClothesForm/<int:id>', views.ClothesFormDeleteView.as_view(), name='clothesFormDelete'),
    path('clothesItemForm/', views.ClothesItemFormView.as_view(), name='clothesItemForm'),
    path('updateClothesItemForm/<int:id>', views.ClothesItemFormUpdateView.as_view(), name='clothesItemFormUpdate'),
    path('deleteClothesItemForm/<int:id>', views.ClothesItemFormDeleteView.as_view(), name='clothesItemFormDelete'),
]

shopQ2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('book/', include('book.urls')),
    path('mobilephone/', include('mobilephone.urls')),
    path('clothes/', include('clothes.urls')),
    path('contact/', include('contact.urls')),
    path('', include("django.contrib.auth.urls")),
    path('cart/', include('cart.urls')),
]

clothes/models.py
from django.db import models

# Create your models here.
class TypeClothes(models.Model):
    name = models.CharField(default='', max_length=50)
    description = models.TextField(default='')
    sex = models.CharField(default='', max_length=50)

    def __str__(self):
        return self.name

class BrandClothes(models.Model):
    name = models.CharField(default='', max_length=50)
    address = models.TextField(default='')

    def __str__(self):
        return self.name


class ClothesA(models.Model):
    name = models.CharField(max_length=50, default='')
    collection = models.CharField(max_length=50, default='')
    material = models.CharField(max_length=50, default='')
    size = models.CharField(max_length=50, default='')
    color = models.CharField(max_length=50, default='')
    image = models.TextField(max_length=255, default='https://assets.vogue.com/photos/62274b72c0d4fbe60f143e7e/master/w_2560%2Cc_limit/00001-chanel-fall-2022-ready-to-wear-paris-credit-gorunway.jpg')
    typeClothes = models.ForeignKey(TypeClothes, on_delete=models.CASCADE)
    brandClothes = models.ForeignKey(BrandClothes, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class ClothesItem(models.Model):
    clothes = models.ForeignKey(ClothesA, on_delete=models.CASCADE)
    price = models.FloatField(max_length=50)
    discount = models.CharField(max_length=50)
    inventory = models.IntegerField(default=0)

clothes/forms.py
from django import forms
from .models import TypeClothes, BrandClothes, ClothesA, ClothesItem

class TypeClothesForm(forms.ModelForm):
    class Meta:
        model = TypeClothes
        fields = '__all__'

class BrandClothesForm(forms.ModelForm):
    class Meta:
        model = BrandClothes
        fields = '__all__'


class ClothesForm(forms.ModelForm):
    class Meta:
        model = ClothesA
        fields = '__all__'


class ClothesItemForm(forms.ModelForm):
    class Meta:
        model = ClothesItem
        fields = '__all__'

clothes/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from django.shortcuts import redirect

from .models import TypeClothes, BrandClothes, ClothesA, ClothesItem
from .forms import TypeClothesForm, BrandClothesForm, ClothesForm, ClothesItemForm

# Create your views here.
class ClothesABC(View):
    def get(self, request):
        clothesItemList = ClothesItem.objects.all()
        return render(request, 'clothes/clothes.html', {
            'clothesItemList': clothesItemList,
        })


class ClothesController(View):
    def get(self, request):
        typeClothesList = TypeClothes.objects.all()
        brandClothesList = BrandClothes.objects.all()
        clothesList = ClothesA.objects.all()
        clothesItemList = ClothesItem.objects.all()
        return render(request, 'clothes/clothesController.html', {
            'typeClothesList': typeClothesList,
            'brandClothesList': brandClothesList,
            'clothesList': clothesList,
            'clothesItemList': clothesItemList,
        })

#----------------------- TypeClothes ------------------------------
class TypeClothesFormView(View):
    def get(self, request):
        af = TypeClothesForm()
        return render(request, 'clothes/clothesForm.html', {'af': af})
    def post(self, request):
        if request.method == 'POST':
            typeClothesForm = TypeClothesForm(request.POST)
            if typeClothesForm.is_valid():
                typeClothesForm.save()
                return redirect('/clothes/clothesController')


class TypeClothesFormUpdateView(View):
    def get(self, request, id):
        typeClothes = TypeClothes.objects.get(id=id)
        af = TypeClothesForm(instance=typeClothes)
        return render(request, 'clothes/clothesForm.html', {'af': af})
    def post(self, request, id):
        if request.method == 'POST':
            typeClothes = TypeClothes.objects.get(id=id)
            typeClothesForm = TypeClothesForm(request.POST, instance=typeClothes)
            if typeClothesForm.is_valid():
                typeClothesForm.save()
                return redirect('/clothes/clothesController')


class TypeClothesFormDeleteView(View):
    def get(self, request, id):
        typeClothes = TypeClothes.objects.get(id=id)
        af = TypeClothesForm(instance=typeClothes)
        return render(request, 'clothes/delete.html', {'af': af, 'item': typeClothes})
    def post(self, request, id):
        if request.method == 'POST':
            typeClothes = TypeClothes.objects.get(id=id)
            typeClothes.delete()
            return redirect('/clothes/clothesController')


#----------------------- BrandClothes ------------------------------
class BrandClothesFormView(View):
    def get(self, request):
        af = BrandClothesForm()
        return render(request, 'clothes/clothesForm.html', {'af': af})
    def post(self, request):
        if request.method == 'POST':
            brandClothesForm = BrandClothesForm(request.POST)
            if brandClothesForm.is_valid():
                brandClothesForm.save()
                return redirect('/clothes/clothesController')


class BrandClothesFormUpdateView(View):
    def get(self, request, id):
        brandClothes = BrandClothes.objects.get(id=id)
        af = BrandClothesForm(instance=brandClothes)
        return render(request, 'clothes/clothesForm.html', {'af': af})
    def post(self, request, id):
        if request.method == 'POST':
            brandClothes = BrandClothes.objects.get(id=id)
            brandClothesForm = BrandClothesForm(request.POST, instance=brandClothes)
            if brandClothesForm.is_valid():
                brandClothesForm.save()
                return redirect('/clothes/clothesController')


class BrandClothesFormDeleteView(View):
    def get(self, request, id):
        brandClothes = BrandClothes.objects.get(id=id)
        af = BrandClothesForm(instance=brandClothes)
        return render(request, 'clothes/delete.html', {'af': af, 'item': brandClothes})
    def post(self, request, id):
        if request.method == 'POST':
            brandClothes = BrandClothes.objects.get(id=id)
            brandClothes.delete()
            return redirect('/clothes/clothesController')


#----------------------- Clothes ------------------------------
class ClothesFormView(View):
    def get(self, request):
        af = ClothesForm()
        return render(request, 'clothes/clothesForm.html', {'af': af})
    def post(self, request):
        if request.method == 'POST':
            clothesForm = ClothesForm(request.POST)
            if clothesForm.is_valid():
                clothesForm.save()
                return redirect('/clothes/clothesController')


class ClothesFormUpdateView(View):
    def get(self, request, id):
        clothes = ClothesA.objects.get(id=id)
        af = ClothesForm(instance=clothes)
        return render(request, 'clothes/clothesForm.html', {'af': af})
    def post(self, request, id):
        if request.method == 'POST':
            clothes = ClothesA.objects.get(id=id)
            clothesForm = ClothesForm(request.POST, instance=clothes)
            if clothesForm.is_valid():
                clothesForm.save()
                return redirect('/clothes/clothesController')


class ClothesFormDeleteView(View):
    def get(self, request, id):
        clothes = ClothesA.objects.get(id=id)
        af = ClothesForm(instance=clothes)
        return render(request, 'clothes/delete.html', {'af': af, 'item': clothes})
    def post(self, request, id):
        if request.method == 'POST':
            clothes = ClothesA.objects.get(id=id)
            clothes.delete()
            return redirect('/clothes/clothesController')


#----------------------- ClothesItem ------------------------------
class ClothesItemFormView(View):
    def get(self, request):
        af = ClothesItemForm()
        return render(request, 'clothes/clothesForm.html', {'af': af})
    def post(self, request):
        if request.method == 'POST':
            clothesItemForm = ClothesItemForm(request.POST)
            if clothesItemForm.is_valid():
                clothesItemForm.save()
                return redirect('/clothes/clothesController')


class ClothesItemFormUpdateView(View):
    def get(self, request, id):
        clothesItem = ClothesItem.objects.get(id=id)
        af = ClothesItemForm(instance=clothesItem)
        return render(request, 'clothes/clothesForm.html', {'af': af})
    def post(self, request, id):
        if request.method == 'POST':
            clothesItem = ClothesItem.objects.get(id=id)
            clothesItemForm = ClothesItemForm(request.POST, instance=clothesItem)
            if clothesItemForm.is_valid():
                clothesItemForm.save()
                return redirect('/clothes/clothesController')


class ClothesItemFormDeleteView(View):
    def get(self, request, id):
        clothesItem = ClothesItem.objects.get(id=id)
        af = ClothesItemForm(instance=clothesItem)
        return render(request, 'clothes/delete.html', {'af': af, 'item': clothesItem})
    def post(self, request, id):
        if request.method == 'POST':
            clothesItem = ClothesItem.objects.get(id=id)
            clothesItem.delete()
            return redirect('/clothes/clothesController')

clothes/templates/clothes/clothes.html
{% extends 'home/base.html' %}
{% block content %}
    <!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:250px">

  <!-- Push down content on small screens -->
  <div class="w3-hide-large" style="margin-top:83px"></div>

  <!-- Top header -->
  <header class="w3-container w3-xlarge">
    <p class="w3-left">BOOK</p>
    <p class="w3-right">
      <i class="fa fa-shopping-cart w3-margin-right"></i>
      <i class="fa fa-search"></i>
    </p>
  </header>

  <!-- Image header -->
  <div class="w3-display-container w3-container">
    <img src="https://previews.123rf.com/images/goodstudio/goodstudio1909/goodstudio190900067/130218841-plantilla-de-
    banner-para-desfile-de-modas-con-modelos-top-con-ropa-de-temporada-de-moda-caminando-po.jpg" alt="Jeans" style="width:100%">
    <div class="w3-display-topleft w3-text-white" style="padding:24px 48px">
      <h1 class="w3-jumbo w3-hide-small">New Fashion</h1>
      <h1 class="w3-hide-large w3-hide-medium">New Fashion</h1>
      <h1 class="w3-hide-small">FASHION HOT 2022</h1>
      <p><a href="#jeans" class="w3-button w3-black w3-padding-large w3-large">SHOP NOW</a></p>
    </div>
  </div>

  <div class="w3-container w3-text-grey" id="jeans">
    <p> items</p>
  </div>

  <!-- Product grid -->
  <div class="w3-row w3-grayscale">
    {% for clothesItem in clothesItemList %}
    <div class="w3-col l3 s6">
      <div class="w3-container">
        <div class="w3-display-container">
          <img src="{{ clothesItem.clothes.image }}"
             style="width:100%;
             height:300px;
             object-fit:cover;
             object-position:50% 50%;"
          >
          <span class="w3-tag w3-display-topleft">Sale {{ clothesItem.discount }}</span>
          <div class="w3-display-middle w3-display-hover">
            <button class="w3-button w3-black">Buy now <i class="fa fa-shopping-cart"></i></button>
          </div>
        </div>
        <p>{{ clothesItem.clothes.title }}<br><b class="w3-text-red">{{ clothesItem.price }}</b></p>
      </div>
    </div>
    {% endfor %}
  </div>

  <!-- Subscribe section -->
  <div class="w3-container w3-black w3-padding-32">
    <h1>Subscribe</h1>
    <p>To get special offers and VIP treatment:</p>
    <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail" style="width:100%"></p>
    <button type="button" class="w3-button w3-red w3-margin-bottom">Subscribe</button>
  </div>

  <!-- Footer -->
  <footer class="w3-padding-64 w3-light-grey w3-small w3-center" id="footer">
    <div class="w3-row-padding">
      <div class="w3-col s4">
        <h4>Contact</h4>
        <p>Questions? Go ahead.</p>
        <form action="/action_page.php" target="_blank">
          <p><input class="w3-input w3-border" type="text" placeholder="Name" name="Name" required></p>
          <p><input class="w3-input w3-border" type="text" placeholder="Email" name="Email" required></p>
          <p><input class="w3-input w3-border" type="text" placeholder="Subject" name="Subject" required></p>
          <p><input class="w3-input w3-border" type="text" placeholder="Message" name="Message" required></p>
          <button type="submit" class="w3-button w3-block w3-black">Send</button>
        </form>
      </div>

      <div class="w3-col s4">
        <h4>About</h4>
        <p><a href="#">About us</a></p>
        <p><a href="#">We're hiring</a></p>
        <p><a href="#">Support</a></p>
        <p><a href="#">Find store</a></p>
        <p><a href="#">Shipment</a></p>
        <p><a href="#">Payment</a></p>
        <p><a href="#">Gift card</a></p>
        <p><a href="#">Return</a></p>
        <p><a href="#">Help</a></p>
      </div>

      <div class="w3-col s4 w3-justify">
        <h4>Store</h4>
        <p><i class="fa fa-fw fa-map-marker"></i> Company Name</p>
        <p><i class="fa fa-fw fa-phone"></i> 0044123123</p>
        <p><i class="fa fa-fw fa-envelope"></i> ex@mail.com</p>
        <h4>We accept</h4>
        <p><i class="fa fa-fw fa-cc-amex"></i> Amex</p>
        <p><i class="fa fa-fw fa-credit-card"></i> Credit Card</p>
        <br>
        <i class="fa fa-facebook-official w3-hover-opacity w3-large"></i>
        <i class="fa fa-instagram w3-hover-opacity w3-large"></i>
        <i class="fa fa-snapchat w3-hover-opacity w3-large"></i>
        <i class="fa fa-pinterest-p w3-hover-opacity w3-large"></i>
        <i class="fa fa-twitter w3-hover-opacity w3-large"></i>
        <i class="fa fa-linkedin w3-hover-opacity w3-large"></i>
      </div>
    </div>
  </footer>

  <div class="w3-black w3-center w3-padding-24">Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-opacity">w3.css</a></div>

  <!-- End page content -->
</div>
{% endblock %}

clothes/templates/clothes/clothesController.html
{% extends 'home/base.html' %}
{% block content %}
    <!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:250px">

  <!-- Push down content on small screens -->
  <div class="w3-hide-large" style="margin-top:83px"></div>

  <!-- Top header -->
  <header class="w3-container w3-xlarge">
    <p class="w3-left">BOOK CONTROLLER</p>
    <p class="w3-right">
      <i class="fa fa-shopping-cart w3-margin-right"></i>
      <i class="fa fa-search"></i>
    </p>
  </header>

  <!-- Image header -->

  <!-- Product grid -->
  <div class="w3-row w3-grayscale">
    <h2>TypeClothes Table</h2>

    <button><a href="{% url 'clothes:typeClothesForm' %}">Create new type Clothes</a></button>
    <table class="w3-table-all w3-small">
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Sex</th>
        <th>Action</th>
      </tr>
      {% for typeClothes in typeClothesList %}
      <tr>
        <td>{{ typeClothes.name }}</td>
        <td>{{ typeClothes.description }}</td>
        <td>{{ typeClothes.sex }}</td>
        <td>
          <button><a href="{% url 'clothes:typeClothesFormUpdate' typeClothes.id %}">Sửa</a></button>
          <button><a href="{% url 'clothes:typeClothesFormDelete' typeClothes.id %}">Xóa</a></button>
        </td>
      </tr>
      {% endfor %}
    </table>


    <h2>BrandClothes Table</h2>

    <button><a href="{% url 'clothes:brandClothesForm' %}">Create new Brand Clothes</a></button>
    <table class="w3-table-all w3-small">
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Action</th>
      </tr>
      {% for brandClothes in brandClothesList %}
      <tr>
        <td>{{ brandClothes.name }}</td>
        <td>{{ brandClothes.address }}</td>
        <td>
          <button><a href="{% url 'clothes:brandClothesFormUpdate' brandClothes.id %}">Sửa</a></button>
          <button><a href="{% url 'clothes:brandClothesFormDelete' brandClothes.id %}">Xóa</a></button>
        </td>
      </tr>
      {% endfor %}
    </table>


    <h2>Clothes Table</h2>

    <button><a href="{% url 'clothes:clothesForm' %}">Create new clothes</a></button>
    <table class="w3-table-all w3-small">
      <tr>
        <th>id</th>
        <th>name</th>
        <th>collection</th>
        <th>material</th>
        <th>size</th>
        <th>color</th>
        <th>image</th>
        <th>Type</th>
        <th>Brand</th>
        <th>Action</th>
      </tr>
      {% for clothes in clothesList %}
      <tr>
        <td>{{ clothes.id }}</td>
        <td>{{ clothes.name }}</td>
        <td>{{ clothes.collection }}</td>
        <td>{{ clothes.material }}</td>
        <td>{{ clothes.size }}</td>
        <td>{{ clothes.color }}</td>
        <td>{{ clothes.image }}</td>
        <td>{{ clothes.typeClothes.name }}</td>
        <td>{{ clothes.brandClothes.name }}</td>
        <td>
          <button><a href="{% url 'clothes:clothesFormUpdate' clothes.id %}">Sửa</a></button>
          <button><a href="{% url 'clothes:clothesFormDelete' clothes.id %}">Xóa</a></button>
        </td>
      </tr>
      {% endfor %}
    </table>


    <h2>ClothesItem Table</h2>

    <button><a href="{% url 'clothes:clothesItemForm' %}">Create new clothes Item</a></button>
    <table class="w3-table-all w3-small">
      <tr>
        <th>id</th>
        <th>name</th>
        <th>price</th>
        <th>discount</th>
        <th>inventory</th>
        <th>Action</th>
      </tr>
      {% for clothesItem in clothesItemList %}
      <tr>
        <td>{{ clothesItem.id }}</td>
        <td>{{ clothesItem.clothes.name }}</td>
        <td>{{ clothesItem.price }}</td>
        <td>{{ clothesItem.discount }}</td>
        <td>{{ clothesItem.inventory }}</td>
        <td>
          <button><a href="{% url 'clothes:clothesItemFormUpdate' clothesItem.id %}">Sửa</a></button>
          <button><a href="{% url 'clothes:clothesItemFormDelete' clothesItem.id %}">Xóa</a></button>
        </td>
      </tr>
      {% endfor %}
    </table>

  </div>

  <!-- End page content -->
</div>
{% endblock %}

clothes/templates/clothes/clothesForm.html
{% extends 'home/base.html' %}
{% block content %}
    <!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:250px">

  <!-- Push down content on small screens -->
  <div class="w3-hide-large" style="margin-top:83px"></div>

  <!-- Top header -->
  <header class="w3-container w3-xlarge">
    <p class="w3-left">CLOTHES CONTROLLER</p>
    <p class="w3-right">
      <i class="fa fa-shopping-cart w3-margin-right"></i>
      <i class="fa fa-search"></i>
    </p>
  </header>

  <!-- Product grid -->
  <div class="w3-row w3-grayscale">
    <h2>Form</h2>
    <form action="" method="post">
      {% csrf_token %}
      {{ af.as_p }}
      <button type="submit">Xác Nhận</button>
    </form>
  </div>

  <!-- End page content -->
</div>
{% endblock %}

clothes/templates/clothes/delete.html
{% extends 'home/base.html' %}
{% block content %}
    <!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:250px">

  <!-- Push down content on small screens -->
  <div class="w3-hide-large" style="margin-top:83px"></div>

  <!-- Top header -->
  <header class="w3-container w3-xlarge">
    <p class="w3-left">BOOK CONTROLLER</p>
    <p class="w3-right">
      <i class="fa fa-shopping-cart w3-margin-right"></i>
      <i class="fa fa-search"></i>
    </p>
  </header>

  <!-- Product grid -->
  <div class="w3-row w3-grayscale">
    <h2>Authors Form</h2>
    <p>Bạn thực sự muốn xóa {{ item.name }}</p>
    <form action="" method="post">
      {% csrf_token %}
      <p><a href="{% url 'clothes:clothesController' %}">cancer</a></p>
      <button type="submit">Xác nhận</button>
    </form>
  </div>

  <!-- End page content -->
</div>
{% endblock %}