book/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    path('', views.Book.as_view(), name='book'),
    path('bookController/', views.BookController.as_view(), name='bookController'),
    path('authorForm/', views.AuthorFormView.as_view(), name='authorForm'),
    path('updateAuthorForm/<int:id>', views.AuthorFormUpdateView.as_view(), name='authorFormUpdate'),
    path('deleteAuthorForm/<int:id>', views.AuthorFormDeleteView.as_view(), name='authorFormDelete'),
    path('categoryForm/', views.CategoryFormView.as_view(), name='categoryForm'),
    path('updateCategoryForm/<int:id>', views.CategoryFormUpdateView.as_view(), name='categoryFormUpdate'),
    path('deleteCategoryForm/<int:id>', views.CategoryFormDeleteView.as_view(), name='categoryFormDelete'),
    path('publisherForm/', views.PublisherFormView.as_view(), name='publisherForm'),
    path('updatePublisherForm/<int:id>', views.PublisherFormUpdateView.as_view(), name='publisherFormUpdate'),
    path('deletePublisherForm/<int:id>', views.PublisherFormDeleteView.as_view(), name='publisherFormDelete'),
    path('bookForm/', views.BookFormView.as_view(), name='bookForm'),
    path('updateBookForm/<int:id>', views.BookFormUpdateView.as_view(), name='bookFormUpdate'),
    path('deleteBookForm/<int:id>', views.BookFormDeleteView.as_view(), name='bookFormDelete'),
    path('bookItemForm/', views.BookItemFormView.as_view(), name='bookItemForm'),
    path('updateBookItemForm/<int:id>', views.BookItemFormUpdateView.as_view(), name='bookItemFormUpdate'),
    path('deleteBookItemForm/<int:id>', views.BookItemFormDeleteView.as_view(), name='bookItemFormDelete'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('addcart', views.addcart, name='addcart'),
    path('shoppingcart', views.shoppingcart, name='shoppingcart'),
    path('saveCartAndOrder', views.savecart, name='savecart'),
    path('paypal', views.paypalPay, name='paypal'),
]

clothes/urls.py
from django.urls import path
from . import views

app_name = 'clothes'
urlpatterns = [
    path('', views.ClothesABC.as_view(), name='clothes'),
    path('clothesController/', views.ClothesController.as_view(), name='clothesController'),
    path('typeClothesForm/', views.TypeClothesFormView.as_view(), name='typeClothesForm'),
    path('updateTypeClothesForm/<int:id>', views.TypeClothesFormUpdateView.as_view(), name='typeClothesFormUpdate'),
    path('deleteTypeClothesForm/<int:id>', views.TypeClothesFormDeleteView.as_view(), name='typeClothesFormDelete'),
    path('brandClothesForm/', views.BrandClothesFormView.as_view(), name='brandClothesForm'),
    path('updateBrandClothesForm/<int:id>', views.BrandClothesFormUpdateView.as_view(), name='brandClothesFormUpdate'),
    path('deleteBrandClothesForm/<int:id>', views.BrandClothesFormDeleteView.as_view(), name='brandClothesFormDelete'),
    path('clothesForm/', views.ClothesFormView.as_view(), name='clothesForm'),
    path('updateClothesForm/<int:id>', views.ClothesFormUpdateView.as_view(), name='clothesFormUpdate'),
    path('deleteClothesForm/<int:id>', views.ClothesFormDeleteView.as_view(), name='clothesFormDelete'),
    path('clothesItemForm/', views.ClothesItemFormView.as_view(), name='clothesItemForm'),
    path('updateClothesItemForm/<int:id>', views.ClothesItemFormUpdateView.as_view(), name='clothesItemFormUpdate'),
    path('deleteClothesItemForm/<int:id>', views.ClothesItemFormDeleteView.as_view(), name='clothesItemFormDelete'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'
urlpatterns = [
    path('', views.Contact.as_view(), name='contact'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
admin_name = 'admin'
urlpatterns = [
    path('', views.index, name='home'),
    path('adminpage/', views.adminpage, name='adminpage'),
]

mobilephone/urls.py
from django.urls import path
from . import views

app_name = 'mobilephone'
urlpatterns = [
    path('', views.MobilePhoneABC.as_view(), name='mobilephone'),
    path('mobilephoneController/', views.MobilephoneController.as_view(), name='mobilephoneController'),
    path('mobilephoneForm/', views.MobilePhoneFormView.as_view(), name='mobilephoneForm'),
    path('updateMobilephoneForm/<int:id>', views.MobilePhoneFormUpdateView.as_view(), name='mobilephoneFormUpdate'),
    path('deleteMobilephoneForm/<int:id>', views.MobilePhoneFormDeleteView.as_view(), name='mobilephoneFormDelete'),
    path('mobilephoneItemForm/', views.MobilePhoneItemFormView.as_view(), name='mobilephoneItemForm'),
    path('updateMobileItemphoneForm/<int:id>', views.MobilePhoneItemFormUpdateView.as_view(), name='mobilephoneItemFormUpdate'),
    path('deleteMobileItemphoneForm/<int:id>', views.MobilePhoneItemFormDeleteView.as_view(), name='mobilephoneItemFormDelete'),
]

shopQ2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('book/', include('book.urls')),
    path('mobilephone/', include('mobilephone.urls')),
    path('clothes/', include('clothes.urls')),
    path('contact/', include('contact.urls')),
    path('', include("django.contrib.auth.urls")),
    path('cart/', include('cart.urls')),
]

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template.loader import render_to_string

from book.models import BookItem
# Create your views here.

def index(request):
    return render(request, 'home/index.html')
def adminpage(request):
    return render(request, 'home/admin.html')

home/templates/home/admin.html

<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>ShopQ</title>
    <link rel="stylesheet" href="{% static 'home/style.css' %}">

<!--  ---------------templates----------  -->
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="{% static 'home/font-awesome.min.css' %}">
    <style>
        .w3-sidebar a {font-family: "Roboto", sans-serif}
        body,h1,h2,h3,h4,h5,h6,.w3-wide {font-family: "Montserrat", sans-serif;}
    </style>
</head>
<body>

    <!--  ---------------templates----------  -->

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-bar-block w3-white w3-collapse w3-top" style="z-index:3;width:250px" id="mySidebar">
  <div class="w3-container w3-display-container w3-padding-16">
    <i onclick="w3_close()" class="fa fa-remove w3-hide-large w3-button w3-display-topright"></i>
    <h3 class="w3-wide"><b>LOGO</b></h3>
  </div>
  <div class="w3-padding-64 w3-large w3-text-grey" style="font-weight:bold">
      <div class="menu">
            <ul>
                <li><a href="{% url 'book:bookController' %}">Book Controller</a></li>
                <li><a href="{% url 'mobilephone:mobilephoneController' %}">Mobilephone Controller</a></li>
                <li><a href="{% url 'clothes:clothesController' %}">Clothes Controller</a></li>
            </ul>
        </div>
    
</nav>

<!-- Top menu on small screens -->
<header class="w3-bar w3-top w3-hide-large w3-black w3-xlarge">
  <div class="w3-bar-item w3-padding-24 w3-wide">LOGO</div>
  <a href="{% url 'cart:shoppingcart' %}" class="w3-bar-item w3-button w3-padding-24 w3-right" onclick="w3_open()"><i class="fa fa-bars"></i></a>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

        <div class="content">
            {% block content %}
            {% endblock %}
        </div>

<!-- Newsletter Modal -->
<div id="newsletter" class="w3-modal">
  <div class="w3-modal-content w3-animate-zoom" style="padding:32px">
    <div class="w3-container w3-white w3-center">
      <i onclick="document.getElementById('newsletter').style.display='none'" class="fa fa-remove w3-right w3-button w3-transparent w3-xxlarge"></i>
      <h2 class="w3-wide">NEWSLETTER</h2>
      <p>Join our mailing list to receive updates on new arrivals and special offers.</p>
      <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail"></p>
      <button type="button" class="w3-button w3-padding-large w3-red w3-margin-bottom" onclick="document.getElementById('newsletter').style.display='none'">Subscribe</button>
    </div>
  </div>
</div>

<script>
// Accordion
function myAccFunc() {
  var x = document.getElementById("demoAcc");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}

// Click on the "Jeans" link on page load to open the accordion for demo purposes
document.getElementById("myBtn").click();


// Open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}
</script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    function addCart(id){
        num = 1;
        $.post( "/cart/addcart", {'id':id, 'num':num, 'csrfmiddlewaretoken':'{{csrf_token}}'} , function( data ) {
          alert('Them san pham thanh cong');
        });
    }
</script>
</body>
</html>

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>ShopQ</title>
    <link rel="stylesheet" href="{% static 'home/style.css' %}">

<!--  ---------------templates----------  -->
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="{% static 'home/font-awesome.min.css' %}">
    <style>
        .w3-sidebar a {font-family: "Roboto", sans-serif}
        body,h1,h2,h3,h4,h5,h6,.w3-wide {font-family: "Montserrat", sans-serif;}
    </style>
</head>
<body>

    <!--  ---------------templates----------  -->

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-bar-block w3-white w3-collapse w3-top" style="z-index:3;width:250px" id="mySidebar">
  <div class="w3-container w3-display-container w3-padding-16">
    <i onclick="w3_close()" class="fa fa-remove w3-hide-large w3-button w3-display-topright"></i>
    <h3 class="w3-wide"><b>LOGO</b></h3>
  </div>
  <div class="w3-padding-64 w3-large w3-text-grey" style="font-weight:bold">
      <div class="menu">
            <ul>
                <li><a href="{% url 'home:home' %}">Home</a></li>
                <li><a href="{% url 'book:book' %}">Book</a></li>
                <li><a href="{% url 'mobilephone:mobilephone' %}">Mobilephone</a></li>
                <li><a href="{% url 'clothes:clothes' %}">Clothes</a></li>
                <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                <li><a href="{% url 'cart:shoppingcart' %}">Cart</a></li>

                
            </ul>
        </div>
    
</nav>

<!-- Top menu on small screens -->
<header class="w3-bar w3-top w3-hide-large w3-black w3-xlarge">
  <div class="w3-bar-item w3-padding-24 w3-wide">LOGO</div>
  <a href="{% url 'cart:shoppingcart' %}" class="w3-bar-item w3-button w3-padding-24 w3-right" onclick="w3_open()"><i class="fa fa-bars"></i></a>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

        <div class="content">
            {% block content %}
            {% endblock %}
        </div>

<!-- Newsletter Modal -->
<div id="newsletter" class="w3-modal">
  <div class="w3-modal-content w3-animate-zoom" style="padding:32px">
    <div class="w3-container w3-white w3-center">
      <i onclick="document.getElementById('newsletter').style.display='none'" class="fa fa-remove w3-right w3-button w3-transparent w3-xxlarge"></i>
      <h2 class="w3-wide">NEWSLETTER</h2>
      <p>Join our mailing list to receive updates on new arrivals and special offers.</p>
      <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail"></p>
      <button type="button" class="w3-button w3-padding-large w3-red w3-margin-bottom" onclick="document.getElementById('newsletter').style.display='none'">Subscribe</button>
    </div>
  </div>
</div>

<script>
// Accordion
function myAccFunc() {
  var x = document.getElementById("demoAcc");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}

// Click on the "Jeans" link on page load to open the accordion for demo purposes
document.getElementById("myBtn").click();


// Open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}
</script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    function addCart(id){
        num = 1;
        $.post( "/cart/addcart", {'id':id, 'num':num, 'csrfmiddlewaretoken':'{{csrf_token}}'} , function( data ) {
          alert('Them san pham thanh cong');
        });
    }
</script>
</body>
</html>

home/templates/home/index.html
{% extends 'home/base.html' %}
{% block content %}
    <!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:250px">

  <!-- Push down content on small screens -->
  <div class="w3-hide-large" style="margin-top:83px"></div>

  <!-- Top header -->
  <header class="w3-container w3-xlarge">
    <p class="w3-left">Jeans</p>
     <p class="w3-right">
      <i class="fa fa-shopping-cart w3-margin-right"></i>
      <i class="fa fa-search"></i>
    </p> 
    <a href="http://127.0.0.1:8000/login" style="float:right;font-size: 16px;">Logout</a>  
  </header>

  <!-- Image header -->
  <div class="w3-display-container w3-container">
    <img src="https://cdn.dribbble.com/users/2972384/screenshots/6822537/sale-shopping.png" alt="Jeans" style="width:100%">
    <div class="w3-display-topleft w3-text-white" style="padding:24px 48px">
      <h1 class="w3-jumbo w3-hide-small">New arrivals</h1>
      <h1 class="w3-hide-large w3-hide-medium">New arrivals</h1>
      <h1 class="w3-hide-small">COLLECTION 2016</h1>
      <p><a href="#jeans" class="w3-button w3-black w3-padding-large w3-large">SHOP NOW</a></p>
    </div>
  </div>


  <!-- Product grid -->


  <!-- Subscribe section -->
  <div class="w3-container w3-black w3-padding-32">
    <h1>Subscribe</h1>
    <p>To get special offers and VIP treatment:</p>
    <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail" style="width:100%"></p>
    <button type="button" class="w3-button w3-red w3-margin-bottom">Subscribe</button>
  </div>

  <!-- Footer -->
  <footer class="w3-padding-64 w3-light-grey w3-small w3-center" id="footer">
    <div class="w3-row-padding">
      <div class="w3-col s4">
        <h4>Contact</h4>
        <p>Questions? Go ahead.</p>
        <form action="/action_page.php" target="_blank">
          <p><input class="w3-input w3-border" type="text" placeholder="Name" name="Name" required></p>
          <p><input class="w3-input w3-border" type="text" placeholder="Email" name="Email" required></p>
          <p><input class="w3-input w3-border" type="text" placeholder="Subject" name="Subject" required></p>
          <p><input class="w3-input w3-border" type="text" placeholder="Message" name="Message" required></p>
          <button type="submit" class="w3-button w3-block w3-black">Send</button>
        </form>
      </div>

      <div class="w3-col s4">
        <h4>About</h4>
        <p><a href="#">About us</a></p>
        <p><a href="#">We're hiring</a></p>
        <p><a href="#">Support</a></p>
        <p><a href="#">Find store</a></p>
        <p><a href="#">Shipment</a></p>
        <p><a href="#">Payment</a></p>
        <p><a href="#">Gift card</a></p>
        <p><a href="#">Return</a></p>
        <p><a href="#">Help</a></p>
      </div>

      <div class="w3-col s4 w3-justify">
        <h4>Store</h4>
        <p><i class="fa fa-fw fa-map-marker"></i> Company Name</p>
        <p><i class="fa fa-fw fa-phone"></i> 0044123123</p>
        <p><i class="fa fa-fw fa-envelope"></i> ex@mail.com</p>
        <h4>We accept</h4>
        <p><i class="fa fa-fw fa-cc-amex"></i> Amex</p>
        <p><i class="fa fa-fw fa-credit-card"></i> Credit Card</p>
        <br>
        <i class="fa fa-facebook-official w3-hover-opacity w3-large"></i>
        <i class="fa fa-instagram w3-hover-opacity w3-large"></i>
        <i class="fa fa-snapchat w3-hover-opacity w3-large"></i>
        <i class="fa fa-pinterest-p w3-hover-opacity w3-large"></i>
        <i class="fa fa-twitter w3-hover-opacity w3-large"></i>
        <i class="fa fa-linkedin w3-hover-opacity w3-large"></i>
      </div>
    </div>
  </footer>

  <div class="w3-black w3-center w3-padding-24">Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-opacity">w3.css</a></div>

  <!-- End page content -->
</div>
{% endblock %}