book/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    path('', views.Book.as_view(), name='book'),
    path('bookController/', views.BookController.as_view(), name='bookController'),
    path('authorForm/', views.AuthorFormView.as_view(), name='authorForm'),
    path('updateAuthorForm/<int:id>', views.AuthorFormUpdateView.as_view(), name='authorFormUpdate'),
    path('deleteAuthorForm/<int:id>', views.AuthorFormDeleteView.as_view(), name='authorFormDelete'),
    path('categoryForm/', views.CategoryFormView.as_view(), name='categoryForm'),
    path('updateCategoryForm/<int:id>', views.CategoryFormUpdateView.as_view(), name='categoryFormUpdate'),
    path('deleteCategoryForm/<int:id>', views.CategoryFormDeleteView.as_view(), name='categoryFormDelete'),
    path('publisherForm/', views.PublisherFormView.as_view(), name='publisherForm'),
    path('updatePublisherForm/<int:id>', views.PublisherFormUpdateView.as_view(), name='publisherFormUpdate'),
    path('deletePublisherForm/<int:id>', views.PublisherFormDeleteView.as_view(), name='publisherFormDelete'),
    path('bookForm/', views.BookFormView.as_view(), name='bookForm'),
    path('updateBookForm/<int:id>', views.BookFormUpdateView.as_view(), name='bookFormUpdate'),
    path('deleteBookForm/<int:id>', views.BookFormDeleteView.as_view(), name='bookFormDelete'),
    path('bookItemForm/', views.BookItemFormView.as_view(), name='bookItemForm'),
    path('updateBookItemForm/<int:id>', views.BookItemFormUpdateView.as_view(), name='bookItemFormUpdate'),
    path('deleteBookItemForm/<int:id>', views.BookItemFormDeleteView.as_view(), name='bookItemFormDelete'),
]

mobilephone/urls.py
from django.urls import path
from . import views

app_name = 'mobilephone'
urlpatterns = [
    path('', views.MobilePhoneABC.as_view(), name='mobilephone'),
    path('mobilephoneController/', views.MobilephoneController.as_view(), name='mobilephoneController'),
    path('mobilephoneForm/', views.MobilePhoneFormView.as_view(), name='mobilephoneForm'),
    path('updateMobilephoneForm/<int:id>', views.MobilePhoneFormUpdateView.as_view(), name='mobilephoneFormUpdate'),
    path('deleteMobilephoneForm/<int:id>', views.MobilePhoneFormDeleteView.as_view(), name='mobilephoneFormDelete'),
    path('mobilephoneItemForm/', views.MobilePhoneItemFormView.as_view(), name='mobilephoneItemForm'),
    path('updateMobileItemphoneForm/<int:id>', views.MobilePhoneItemFormUpdateView.as_view(), name='mobilephoneItemFormUpdate'),
    path('deleteMobileItemphoneForm/<int:id>', views.MobilePhoneItemFormDeleteView.as_view(), name='mobilephoneItemFormDelete'),
]

shopQ2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('book/', include('book.urls')),
    path('mobilephone/', include('mobilephone.urls')),
    path('clothes/', include('clothes.urls')),
    path('contact/', include('contact.urls')),
    path('', include("django.contrib.auth.urls")),
    path('cart/', include('cart.urls')),
]

mobilephone/models.py
from django.db import models

# Create your models here.
class MobilePhoneA(models.Model):
    name = models.CharField(max_length=50, default='')
    image = models.TextField(max_length=255, default='https://cdn-amz.fadoglobal.io/images/I/71hIfcIPyxS.jpg')
    storage = models.IntegerField(default=0)
    screensize = models.CharField(max_length=50, default='')
    ram = models.CharField(max_length=50, default='')
    chip = models.CharField(max_length=50, default='')
    os = models.CharField(max_length=50, default='')
    description = models.TextField(max_length=255, default='')

    def __str__(self):
        return self.name


class MobilePhoneItem(models.Model):
    mobilePhone = models.ForeignKey(MobilePhoneA, on_delete=models.CASCADE)
    price = models.FloatField(max_length=50)
    discount = models.CharField(max_length=50)
    inventory = models.IntegerField(default=0)

mobilephone/forms.py
from django import forms
from .models import MobilePhoneA, MobilePhoneItem

class MobilePhoneForm(forms.ModelForm):
    class Meta:
        model = MobilePhoneA
        fields = '__all__'


class MobilePhoneItemForm(forms.ModelForm):
    class Meta:
        model = MobilePhoneItem
        fields = '__all__'

mobilephone/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from django.shortcuts import redirect

from .models import MobilePhoneA, MobilePhoneItem
from .forms import MobilePhoneForm, MobilePhoneItemForm

# Create your views here.
class MobilePhoneABC(View):
    def get(self, request):
        mobilephoneItemList = MobilePhoneItem.objects.all()
        return render(request, 'mobilephone/mobilePhone.html', {
            'mobilephoneItemList': mobilephoneItemList,
        })


class MobilephoneController(View):
    def get(self, request):
        mobilephoneAList = MobilePhoneA.objects.all()
        mobilephoneItemList = MobilePhoneItem.objects.all()
        return render(request, 'mobilephone/mobilephoneController.html', {
            'mobilephoneAList': mobilephoneAList,
            'mobilephoneItemList': mobilephoneItemList,
        })


#----------------------- mobilePhone ------------------------------
class MobilePhoneFormView(View):
    def get(self, request):
        af = MobilePhoneForm()
        return render(request, 'mobilephone/mobilephoneForm.html', {'af': af})
    def post(self, request):
        if request.method == 'POST':
            mobilePhoneForm = MobilePhoneForm(request.POST)
            if mobilePhoneForm.is_valid():
                mobilePhoneForm.save()
                return redirect('/mobilephone/mobilephoneController/')


class MobilePhoneFormUpdateView(View):
    def get(self, request, id):
        mobilePhone = MobilePhoneA.objects.get(id=id)
        af = MobilePhoneForm(instance=mobilePhone)
        return render(request, 'mobilephone/mobilephoneForm.html', {'af': af})
    def post(self, request, id):
        if request.method == 'POST':
            mobilePhone = MobilePhoneA.objects.get(id=id)
            mobilePhoneForm = MobilePhoneForm(request.POST, instance=mobilePhone)
            if mobilePhoneForm.is_valid():
                mobilePhoneForm.save()
                return redirect('/mobilephone/mobilephoneController/')


class MobilePhoneFormDeleteView(View):
    def get(self, request, id):
        mobilePhone = MobilePhoneA.objects.get(id=id)
        af = MobilePhoneForm(instance=mobilePhone)
        return render(request, 'mobilephone/delete.html', {'af': af, 'item': mobilePhone})
    def post(self, request, id):
        if request.method == 'POST':
            mobilePhone = MobilePhoneA.objects.get(id=id)
            mobilePhone.delete()
            return redirect('/mobilephone/mobilephoneController/')


#----------------------- MobilePhoneItem ------------------------------
class MobilePhoneItemFormView(View):
    def get(self, request):
        af = MobilePhoneItemForm()
        return render(request, 'mobilephone/mobilephoneForm.html', {'af': af})
    def post(self, request):
        if request.method == 'POST':
            mobilePhoneItemForm = MobilePhoneItemForm(request.POST)
            if mobilePhoneItemForm.is_valid():
                mobilePhoneItemForm.save()
                return redirect('/mobilephone/mobilephoneController/')


class MobilePhoneItemFormUpdateView(View):
    def get(self, request, id):
        mobilePhoneItem = MobilePhoneItem.objects.get(id=id)
        af = MobilePhoneForm(instance=mobilePhoneItem)
        return render(request, 'mobilephone/mobilephoneForm.html', {'af': af})
    def post(self, request, id):
        if request.method == 'POST':
            mobilePhoneItem = MobilePhoneItem.objects.get(id=id)
            mobilePhoneItemForm = MobilePhoneItemForm(request.POST, instance=mobilePhoneItem)
            if mobilePhoneItemForm.is_valid():
                mobilePhoneItemForm.save()
                return redirect('/mobilephone/mobilephoneController/')


class MobilePhoneItemFormDeleteView(View):
    def get(self, request, id):
        mobilePhoneItem = MobilePhoneItem.objects.get(id=id)
        af = MobilePhoneItemForm(instance=mobilePhoneItem)
        return render(request, 'mobilephone/delete.html', {'af': af, 'item': mobilePhoneItem})
    def post(self, request, id):
        if request.method == 'POST':
            mobilePhoneItem = MobilePhoneItem.objects.get(id=id)
            mobilePhoneItem.delete()
            return redirect('/mobilephone/mobilephoneController/')

mobilephone/templates/mobilephone/delete.html
{% extends 'home/base.html' %}
{% block content %}
    <!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:250px">

  <!-- Push down content on small screens -->
  <div class="w3-hide-large" style="margin-top:83px"></div>

  <!-- Top header -->
  <header class="w3-container w3-xlarge">
    <p class="w3-left">BOOK CONTROLLER</p>
    <p class="w3-right">
      <i class="fa fa-shopping-cart w3-margin-right"></i>
      <i class="fa fa-search"></i>
    </p>
  </header>

  <!-- Product grid -->
  <div class="w3-row w3-grayscale">
    <h2>Authors Form</h2>
    <p>Bạn thực sự muốn xóa {{ item.name }}</p>
    <form action="" method="post">
      {% csrf_token %}
      <p><a href="{% url 'mobilephone:mobilephoneController' %}">cancer</a></p>
      <button type="submit">Xác nhận</button>
    </form>
  </div>

  <!-- End page content -->
</div>
{% endblock %}

mobilephone/templates/mobilephone/mobilePhone.html
{% extends 'home/base.html' %}
{% block content %}
    <!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:250px">

  <!-- Push down content on small screens -->
  <div class="w3-hide-large" style="margin-top:83px"></div>

  <!-- Top header -->
  <header class="w3-container w3-xlarge">
    <p class="w3-left">BOOK</p>
    <p class="w3-right">
      <i class="fa fa-shopping-cart w3-margin-right"></i>
      <i class="fa fa-search"></i>
    </p>
  </header>

  <!-- Image header -->
  <div class="w3-display-container w3-container">
    <img src="https://png.pngtree.com/thumb_back/fw800/back_our/20190621/ourmid/pngtree-cool-new-mobile-phone-promotion-purple-banner-image_183067.jpg" alt="Jeans" style="width:100%">
    <div class="w3-display-topleft w3-text-white" style="padding:24px 48px">
      <h1 class="w3-jumbo w3-hide-small">New PHONE</h1>
      <h1 class="w3-hide-large w3-hide-medium">New PHONE</h1>
      <h1 class="w3-hide-small">BEST PHONE FOR 2022</h1>
      <p><a href="#jeans" class="w3-button w3-black w3-padding-large w3-large">SHOP NOW</a></p>
    </div>
  </div>

  <div class="w3-container w3-text-grey" id="jeans">
    <p>8 items</p>
  </div>

  <!-- Product grid -->
  <div class="w3-row w3-grayscale">
    {% for mobilephoneItem in mobilephoneItemList %}
    <div class="w3-col l3 s6">
      <div class="w3-container">
        <div class="w3-display-container">
          <img src="{{ mobilephoneItem.mobilePhone.image }}"
             style="width:100%;
             height:300px;
             object-fit:cover;
             object-position:50% 50%;"
          >
          <span class="w3-tag w3-display-topleft">Sale {{ mobilephoneItem.discount }}</span>
          <div class="w3-display-middle w3-display-hover">
            <button class="w3-button w3-black">Buy now <i class="fa fa-shopping-cart"></i></button>
          </div>
        </div>
        <p>{{ mobilephoneItem.mobilePhone.title }}<br><b class="w3-text-red">{{ mobilephoneItem.price }}</b></p>
      </div>
    </div>
    {% endfor %}
  </div>

  <!-- Subscribe section -->
  <div class="w3-container w3-black w3-padding-32">
    <h1>Subscribe</h1>
    <p>To get special offers and VIP treatment:</p>
    <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail" style="width:100%"></p>
    <button type="button" class="w3-button w3-red w3-margin-bottom">Subscribe</button>
  </div>

  <!-- Footer -->
  <footer class="w3-padding-64 w3-light-grey w3-small w3-center" id="footer">
    <div class="w3-row-padding">
      <div class="w3-col s4">
        <h4>Contact</h4>
        <p>Questions? Go ahead.</p>
        <form action="/action_page.php" target="_blank">
          <p><input class="w3-input w3-border" type="text" placeholder="Name" name="Name" required></p>
          <p><input class="w3-input w3-border" type="text" placeholder="Email" name="Email" required></p>
          <p><input class="w3-input w3-border" type="text" placeholder="Subject" name="Subject" required></p>
          <p><input class="w3-input w3-border" type="text" placeholder="Message" name="Message" required></p>
          <button type="submit" class="w3-button w3-block w3-black">Send</button>
        </form>
      </div>

      <div class="w3-col s4">
        <h4>About</h4>
        <p><a href="#">About us</a></p>
        <p><a href="#">We're hiring</a></p>
        <p><a href="#">Support</a></p>
        <p><a href="#">Find store</a></p>
        <p><a href="#">Shipment</a></p>
        <p><a href="#">Payment</a></p>
        <p><a href="#">Gift card</a></p>
        <p><a href="#">Return</a></p>
        <p><a href="#">Help</a></p>
      </div>

      <div class="w3-col s4 w3-justify">
        <h4>Store</h4>
        <p><i class="fa fa-fw fa-map-marker"></i> Company Name</p>
        <p><i class="fa fa-fw fa-phone"></i> 0044123123</p>
        <p><i class="fa fa-fw fa-envelope"></i> ex@mail.com</p>
        <h4>We accept</h4>
        <p><i class="fa fa-fw fa-cc-amex"></i> Amex</p>
        <p><i class="fa fa-fw fa-credit-card"></i> Credit Card</p>
        <br>
        <i class="fa fa-facebook-official w3-hover-opacity w3-large"></i>
        <i class="fa fa-instagram w3-hover-opacity w3-large"></i>
        <i class="fa fa-snapchat w3-hover-opacity w3-large"></i>
        <i class="fa fa-pinterest-p w3-hover-opacity w3-large"></i>
        <i class="fa fa-twitter w3-hover-opacity w3-large"></i>
        <i class="fa fa-linkedin w3-hover-opacity w3-large"></i>
      </div>
    </div>
  </footer>

  <div class="w3-black w3-center w3-padding-24">Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-opacity">w3.css</a></div>

  <!-- End page content -->
</div>
{% endblock %}

mobilephone/templates/mobilephone/mobilePhoneController.html
{% extends 'home/base.html' %}
{% block content %}
    <!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:250px">

  <!-- Push down content on small screens -->
  <div class="w3-hide-large" style="margin-top:83px"></div>

  <!-- Top header -->
  <header class="w3-container w3-xlarge">
    <p class="w3-left">MOBILEPHONE CONTROLLER</p>
    <p class="w3-right">
      <i class="fa fa-shopping-cart w3-margin-right"></i>
      <i class="fa fa-search"></i>
    </p>
  </header>

  <!-- Image header -->

  <!-- Product grid -->
  <div class="w3-row w3-grayscale">

    <h2>MobilePhone Table</h2>

    <button><a href="{% url 'mobilephone:mobilephoneForm' %}">Create new mobilephone</a></button>
    <table class="w3-table-all w3-small">
      <tr>
        <th>Name</th>
        <th>image</th>
        <th>storage</th>
        <th>screensize</th>
        <th>ram</th>
        <th>chip</th>
        <th>os</th>
        <th>description</th>
      </tr>
      {% for mobilephone in mobilephoneAList %}
      <tr>
        <td>{{ mobilephone.name }}</td>
        <td style="max-width: 200px; overflow: hidden; text-overflow: ellipsis">{{ mobilephone.image }}</td>
        <td>{{ mobilephone.storage }}</td>
        <td>{{ mobilephone.screensize }}</td>
        <td>{{ mobilephone.ram }}</td>
        <td>{{ mobilephone.chip }}</td>
        <td>{{ mobilephone.os }}</td>
        <td>{{ mobilephone.description }}</td>
        <td>
          <button><a href="{% url 'mobilephone:mobilephoneFormUpdate' mobilephone.id %}">Sửa</a></button>
          <button><a href="{% url 'mobilephone:mobilephoneFormDelete' mobilephone.id %}">Xóa</a></button>
        </td>
      </tr>
      {% endfor %}
    </table>


    <h2>MobilePhoneItem Table</h2>

    <button><a href="{% url 'mobilephone:mobilephoneItemForm' %}">Create new mobilephone Item</a></button>
    <table class="w3-table-all w3-small">
      <tr>
        <th>ID</th>
        <th>Phone</th>
        <th>price</th>
        <th>discount</th>
        <th>inventory</th>
      </tr>
      {% for mobilephone in mobilephoneItemList %}
      <tr>
        <td>{{ mobilephone.id }}</td>
        <td>{{ mobilephone.mobilePhone.name }}</td>
        <td>{{ mobilephone.price }}</td>
        <td>{{ mobilephone.discount }}</td>
        <td>{{ mobilephone.inventory }}</td>
        <td>
          <button><a href="{% url 'mobilephone:mobilephoneItemFormUpdate' mobilephone.id %}">Sửa</a></button>
          <button><a href="{% url 'mobilephone:mobilephoneItemFormDelete' mobilephone.id %}">Xóa</a></button>
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>

  <!-- End page content -->
</div>
{% endblock %}

mobilephone/templates/mobilephone/mobilephoneForm.html
{% extends 'home/base.html' %}
{% block content %}
    <!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:250px">

  <!-- Push down content on small screens -->
  <div class="w3-hide-large" style="margin-top:83px"></div>

  <!-- Top header -->
  <header class="w3-container w3-xlarge">
    <p class="w3-left">MOBILEPHONE CONTROLLER</p>
    <p class="w3-right">
      <i class="fa fa-shopping-cart w3-margin-right"></i>
      <i class="fa fa-search"></i>
    </p>
  </header>

  <!-- Product grid -->
  <div class="w3-row w3-grayscale">
    <h2>Form</h2>
    <form action="" method="post">
      {% csrf_token %}
      {{ af.as_p }}
      <button type="submit">Xác Nhận</button>
    </form>
  </div>

  <!-- End page content -->
</div>
{% endblock %}