book/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    path('', views.Book.as_view(), name='book'),
    path('bookController/', views.BookController.as_view(), name='bookController'),
    path('authorForm/', views.AuthorFormView.as_view(), name='authorForm'),
    path('updateAuthorForm/<int:id>', views.AuthorFormUpdateView.as_view(), name='authorFormUpdate'),
    path('deleteAuthorForm/<int:id>', views.AuthorFormDeleteView.as_view(), name='authorFormDelete'),
    path('categoryForm/', views.CategoryFormView.as_view(), name='categoryForm'),
    path('updateCategoryForm/<int:id>', views.CategoryFormUpdateView.as_view(), name='categoryFormUpdate'),
    path('deleteCategoryForm/<int:id>', views.CategoryFormDeleteView.as_view(), name='categoryFormDelete'),
    path('publisherForm/', views.PublisherFormView.as_view(), name='publisherForm'),
    path('updatePublisherForm/<int:id>', views.PublisherFormUpdateView.as_view(), name='publisherFormUpdate'),
    path('deletePublisherForm/<int:id>', views.PublisherFormDeleteView.as_view(), name='publisherFormDelete'),
    path('bookForm/', views.BookFormView.as_view(), name='bookForm'),
    path('updateBookForm/<int:id>', views.BookFormUpdateView.as_view(), name='bookFormUpdate'),
    path('deleteBookForm/<int:id>', views.BookFormDeleteView.as_view(), name='bookFormDelete'),
    path('bookItemForm/', views.BookItemFormView.as_view(), name='bookItemForm'),
    path('updateBookItemForm/<int:id>', views.BookItemFormUpdateView.as_view(), name='bookItemFormUpdate'),
    path('deleteBookItemForm/<int:id>', views.BookItemFormDeleteView.as_view(), name='bookItemFormDelete'),
]

shopQ2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('book/', include('book.urls')),
    path('mobilephone/', include('mobilephone.urls')),
    path('clothes/', include('clothes.urls')),
    path('contact/', include('contact.urls')),
    path('', include("django.contrib.auth.urls")),
    path('cart/', include('cart.urls')),
]

book/models.py
from django.db import models

# Create your models here.
from django.db import models


# Create your models here.
class CategoryBook(models.Model):
    name = models.CharField(default='', max_length=50)
    description = models.TextField(default='')

    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(default='', max_length=50)
    address = models.TextField(default='')

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(default='', max_length=50)
    biography = models.TextField(default='')

    def __str__(self):
        return self.name


class BookEn(models.Model):
    ISBN = models.CharField(primary_key=True, max_length=50)
    title = models.TextField(default='')
    summary = models.CharField(max_length=255, default='')
    numberOfPages = models.IntegerField(default=0)
    language = models.CharField(max_length=50, default='')
    image = models.TextField(max_length=255, default='https://cdn5.f-cdn.com/contestentries/1840252/39964678/5fa3d8364496e_thumb900.jpg')
    categoryBook = models.ForeignKey(CategoryBook, on_delete=models.CASCADE)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class BookItem(models.Model):
    book = models.ForeignKey(BookEn, on_delete=models.CASCADE)
    barcode = models.CharField(primary_key=True, max_length=50)
    price = models.FloatField(max_length=50)
    discount = models.CharField(max_length=50)
    inventory = models.IntegerField(default=0)

book/forms.py
from django import forms
from .models import Author, CategoryBook, Publisher, BookEn, BookItem


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'


class PublisherForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = '__all__'


class CategoryBookForm(forms.ModelForm):
    class Meta:
        model = CategoryBook
        fields = '__all__'


class BookForm(forms.ModelForm):
    class Meta:
        model = BookEn
        fields = '__all__'


class BookItemForm(forms.ModelForm):
    class Meta:
        model = BookItem
        fields = '__all__'

book/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from django.shortcuts import redirect

from .models import Author, CategoryBook, Publisher, BookEn, BookItem
from .forms import AuthorForm, CategoryBookForm, PublisherForm, BookForm, BookItemForm

# Create your views here.
class Book(View):
    def get(self, request):
        bookItems = BookItem.objects.all()
        return render(request, 'book/book.html', {
            'bookItems': bookItems,
        })

class BookController(View):
    def get(self, request):
        authorList = Author.objects.all()
        categoryBooks = CategoryBook.objects.all()
        publishers = Publisher.objects.all()
        books = BookEn.objects.all()
        bookItems = BookItem.objects.all()
        return render(request, 'book/bookController.html', {
            'authorList': authorList,
            'categoryBooks': categoryBooks,
            'publishers': publishers,
            'books': books,
            'bookItems': bookItems,
        })


#----------------------- Author ------------------------------
class AuthorFormView(View):
    def get(self, request):
        af = AuthorForm()
        return render(request, 'book/authorForm.html', {'af': af})
    def post(self, request):
        if request.method == 'POST':
            authorForm = AuthorForm(request.POST)
            if authorForm.is_valid():
                authorForm.save()
                return HttpResponse('Them thanh cong')


class AuthorFormUpdateView(View):
    def get(self, request, id):
        author = Author.objects.get(id=id)
        af = AuthorForm(instance=author)
        return render(request, 'book/authorForm.html', {'af': af})
    def post(self, request, id):
        if request.method == 'POST':
            author = Author.objects.get(id=id)
            authorForm = AuthorForm(request.POST, instance=author)
            if authorForm.is_valid():
                authorForm.save()
                return redirect('/book/bookController')


class AuthorFormDeleteView(View):
    def get(self, request, id):
        author = Author.objects.get(id=id)
        af = AuthorForm(instance=author)
        return render(request, 'book/delete.html', {'af': af, 'item': author})
    def post(self, request, id):
        if request.method == 'POST':
            author = Author.objects.get(id=id)
            author.delete()
            return redirect('/book/bookController')

#----------------------- Category ------------------------------
class CategoryFormView(View):
    def get(self, request):
        af = CategoryBookForm()
        return render(request, 'book/authorForm.html', {'af': af})
    def post(self, request):
        if request.method == 'POST':
            categoryForm = CategoryBookForm(request.POST)
            if categoryForm.is_valid():
                categoryForm.save()
                return redirect('/book/bookController')


class CategoryFormUpdateView(View):
    def get(self, request, id):
        category = CategoryBook.objects.get(id=id)
        af = CategoryBookForm(instance=category)
        return render(request, 'book/authorForm.html', {'af': af})
    def post(self, request, id):
        if request.method == 'POST':
            category = CategoryBook.objects.get(id=id)
            categoryForm = CategoryBookForm(request.POST, instance=category)
            if categoryForm.is_valid():
                categoryForm.save()
                return redirect('/book/bookController')


class CategoryFormDeleteView(View):
    def get(self, request, id):
        category = CategoryBook.objects.get(id=id)
        af = AuthorForm(instance=category)
        return render(request, 'book/delete.html', {'af': af, 'item': category})
    def post(self, request, id):
        if request.method == 'POST':
            category = CategoryBook.objects.get(id=id)
            category.delete()
            return redirect('/book/bookController')


#----------------------- Publisher ------------------------------
class PublisherFormView(View):
    def get(self, request):
        af = PublisherForm()
        return render(request, 'book/authorForm.html', {'af': af})
    def post(self, request):
        if request.method == 'POST':
            publisherForm = PublisherForm(request.POST)
            if publisherForm.is_valid():
                publisherForm.save()
                return redirect('/book/bookController')


class PublisherFormUpdateView(View):
    def get(self, request, id):
        publisher = Publisher.objects.get(id=id)
        af = PublisherForm(instance=publisher)
        return render(request, 'book/authorForm.html', {'af': af})
    def post(self, request, id):
        if request.method == 'POST':
            publisher = Publisher.objects.get(id=id)
            publisherForm = PublisherForm(request.POST, instance=publisher)
            if publisherForm.is_valid():
                publisherForm.save()
                return redirect('/book/bookController')


class PublisherFormDeleteView(View):
    def get(self, request, id):
        publisher = Publisher.objects.get(id=id)
        af = PublisherForm(instance=publisher)
        return render(request, 'book/delete.html', {'af': af, 'item': publisher})
    def post(self, request, id):
        if request.method == 'POST':
            publisher = Publisher.objects.get(id=id)
            publisher.delete()
            return redirect('/book/bookController')


#----------------------- Book ------------------------------
class BookFormView(View):
    def get(self, request):
        af = BookForm()
        return render(request, 'book/authorForm.html', {'af': af})
    def post(self, request):
        if request.method == 'POST':
            bookForm = BookForm(request.POST)
            if bookForm.is_valid():
                bookForm.save()
                return redirect('/book/bookController')
            else:
                HttpResponse('Các trường không họp lệ (có thể do trùng id)')
        else:
            HttpResponse('Các trường không họp lệ (có thể do trùng id)')


class BookFormUpdateView(View):
    def get(self, request, id):
        book = BookEn.objects.get(ISBN=id)
        af = BookForm(instance=book)
        return render(request, 'book/authorForm.html', {'af': af})
    def post(self, request, id):
        if request.method == 'POST':
            book = BookEn.objects.get(ISBN=id)
            bookForm = BookForm(request.POST, instance=book)
            if bookForm.is_valid():
                bookForm.save()
                return redirect('/book/bookController')


class BookFormDeleteView(View):
    def get(self, request, id):
        book = BookEn.objects.get(ISBN=id)
        af = BookForm(instance=book)
        return render(request, 'book/delete.html', {'af': af, 'item': book})
    def post(self, request, id):
        if request.method == 'POST':
            book = BookEn.objects.get(ISBN=id)
            book.delete()
            return redirect('/book/bookController')

# ----------------------- BookItem ------------------------------
class BookItemFormView(View):
    def get(self, request):
        af = BookItemForm()
        return render(request, 'book/authorForm.html', {'af': af})

    def post(self, request):
        if request.method == 'POST':
            bookItemForm = BookItemForm(request.POST)
            if bookItemForm.is_valid():
                bookItemForm.save()
                return redirect('/book/bookController')
            else:
                HttpResponse('Các trường không họp lệ (có thể do trùng id)')
        else:
            HttpResponse('Các trường không họp lệ (có thể do trùng id)')

class BookItemFormUpdateView(View):
    def get(self, request, id):
        bookItem = BookItem.objects.get(barcode=id)
        af = BookItemForm(instance=bookItem)
        return render(request, 'book/authorForm.html', {'af': af})

    def post(self, request, id):
        if request.method == 'POST':
            bookItem = BookItem.objects.get(barcode=id)
            bookItemForm = BookItemForm(request.POST, instance=bookItem)
            if bookItemForm.is_valid():
                bookItemForm.save()
                return redirect('/book/bookController')

class BookItemFormDeleteView(View):
    def get(self, request, id):
        bookItem = BookItem.objects.get(barcode=id)
        af = BookItemForm(instance=bookItem)
        return render(request, 'book/delete.html', {'af': af, 'item': bookItem})

    def post(self, request, id):
        if request.method == 'POST':
            bookItem = BookItem.objects.get(barcode=id)
            bookItem.delete()
            return redirect('/book/bookController')

book/templates/book/authorForm.html
{% extends 'home/base.html' %}
{% block content %}
    <!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:250px">

  <!-- Push down content on small screens -->
  <div class="w3-hide-large" style="margin-top:83px"></div>

  <!-- Top header -->
  <header class="w3-container w3-xlarge">
    <p class="w3-left">BOOK CONTROLLER</p>
    <p class="w3-right">
      <i class="fa fa-shopping-cart w3-margin-right"></i>
      <i class="fa fa-search"></i>
    </p>
  </header>

  <!-- Product grid -->
  <div class="w3-row w3-grayscale">
    <h2>Form</h2>
    <form action="" method="post">
      {% csrf_token %}
      {{ af.as_p }}
      <button type="submit">Xác Nhận</button>
    </form>
  </div>

  <!-- End page content -->
</div>
{% endblock %}

book/templates/book/book.html
{% extends 'home/base.html' %}
{% block content %}
    <!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:250px">

  <!-- Push down content on small screens -->
  <div class="w3-hide-large" style="margin-top:83px"></div>

  <!-- Top header -->
  <header class="w3-container w3-xlarge">
    <p class="w3-left">BOOK</p>
    <p class="w3-right">
      <i class="fa fa-shopping-cart w3-margin-right"></i>
      <i class="fa fa-search"></i>
    </p>
  </header>

  <!-- Image header -->
  <div class="w3-display-container w3-container">
    <img src="https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX3672435.jpg" alt="Jeans" style="width:100%">
    <div class="w3-display-topleft w3-text-white" style="padding:24px 48px">
      <h1 class="w3-jumbo w3-hide-small">New Book</h1>
      <h1 class="w3-hide-large w3-hide-medium">New Book</h1>
      <h1 class="w3-hide-small">BOOK HOT 2022</h1>
      <p><a href="#jeans" class="w3-button w3-black w3-padding-large w3-large">SHOP NOW</a></p>
    </div>
  </div>

  <div class="w3-container w3-text-grey" id="jeans">
    <p>8 items</p>
  </div>

  <!-- Product grid -->
  <div class="w3-row w3-grayscale">
    {% for bookItem in bookItems %}
    <div class="w3-col l3 s6">
      <div class="w3-container">
        <div class="w3-display-container">
          <img src="{{ bookItem.book.image }}"
             style="width:100%;
             height:300px;
             object-fit:cover;
             object-position:50% 50%;"
          >
          bookItem.barcode
          <span class="w3-tag w3-display-topleft">Sale {{ bookItem.discount }}</span>
          <div class="w3-display-middle w3-display-hover">
            <button class="w3-button w3-black" onclick="addCart({{bookItem.barcode}})">Buy now <i class="fa fa-shopping-cart"></i></button>
          </div>
        </div>
        <p>{{ bookItem.book.title }}<br><b class="w3-text-red">{{ bookItem.price }}</b></p>
      </div>
    </div>
    {% endfor %}
  </div>

  <!-- Subscribe section -->
  <div class="w3-container w3-black w3-padding-32">
    <h1>Subscribe</h1>
    <p>To get special offers and VIP treatment:</p>
    <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail" style="width:100%"></p>
    <button type="button" class="w3-button w3-red w3-margin-bottom">Subscribe</button>
  </div>

  <!-- Footer -->
  <footer class="w3-padding-64 w3-light-grey w3-small w3-center" id="footer">
    <div class="w3-row-padding">
      <div class="w3-col s4">
        <h4>Contact</h4>
        <p>Questions? Go ahead.</p>
        <form action="/action_page.php" target="_blank">
          <p><input class="w3-input w3-border" type="text" placeholder="Name" name="Name" required></p>
          <p><input class="w3-input w3-border" type="text" placeholder="Email" name="Email" required></p>
          <p><input class="w3-input w3-border" type="text" placeholder="Subject" name="Subject" required></p>
          <p><input class="w3-input w3-border" type="text" placeholder="Message" name="Message" required></p>
          <button type="submit" class="w3-button w3-block w3-black">Send</button>
        </form>
      </div>

      <div class="w3-col s4">
        <h4>About</h4>
        <p><a href="#">About us</a></p>
        <p><a href="#">We're hiring</a></p>
        <p><a href="#">Support</a></p>
        <p><a href="#">Find store</a></p>
        <p><a href="#">Shipment</a></p>
        <p><a href="#">Payment</a></p>
        <p><a href="#">Gift card</a></p>
        <p><a href="#">Return</a></p>
        <p><a href="#">Help</a></p>
      </div>

      <div class="w3-col s4 w3-justify">
        <h4>Store</h4>
        <p><i class="fa fa-fw fa-map-marker"></i> Company Name</p>
        <p><i class="fa fa-fw fa-phone"></i> 0044123123</p>
        <p><i class="fa fa-fw fa-envelope"></i> ex@mail.com</p>
        <h4>We accept</h4>
        <p><i class="fa fa-fw fa-cc-amex"></i> Amex</p>
        <p><i class="fa fa-fw fa-credit-card"></i> Credit Card</p>
        <br>
        <i class="fa fa-facebook-official w3-hover-opacity w3-large"></i>
        <i class="fa fa-instagram w3-hover-opacity w3-large"></i>
        <i class="fa fa-snapchat w3-hover-opacity w3-large"></i>
        <i class="fa fa-pinterest-p w3-hover-opacity w3-large"></i>
        <i class="fa fa-twitter w3-hover-opacity w3-large"></i>
        <i class="fa fa-linkedin w3-hover-opacity w3-large"></i>
      </div>
    </div>
  </footer>

  <div class="w3-black w3-center w3-padding-24">Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-opacity">w3.css</a></div>

  <!-- End page content -->
</div>
{% endblock %}

book/templates/book/bookController.html
{% extends 'home/base.html' %}
{% block content %}
    <!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:250px">

  <!-- Push down content on small screens -->
  <div class="w3-hide-large" style="margin-top:83px"></div>

  <!-- Top header -->
  <header class="w3-container w3-xlarge">
    <p class="w3-left">BOOK CONTROLLER</p>
    <p class="w3-right">
      <i class="fa fa-shopping-cart w3-margin-right"></i>
      <i class="fa fa-search"></i>
    </p>
  </header>

  <!-- Image header -->

  <!-- Product grid -->
  <div class="w3-row w3-grayscale">
    <h2>Authors Table</h2>

    <button><a href="{% url 'book:authorForm' %}">Create new author</a></button>
    <table class="w3-table-all w3-small">
      <tr>
        <th>Name</th>
        <th>Biography</th>
        <th>Action</th>
      </tr>
      {% for author in authorList %}
      <tr>
        <td>{{ author.name }}</td>
        <td>{{ author.biography }}</td>
        <td>
          <button><a href="{% url 'book:authorFormUpdate' author.id %}">Sửa</a></button>
          <button><a href="{% url 'book:authorFormDelete' author.id %}">Xóa</a></button>
        </td>
      </tr>
      {% endfor %}
    </table>


    <h2>CategoryBook Table</h2>

    <button><a href="{% url 'book:categoryForm' %}">Create new category</a></button>
    <table class="w3-table-all w3-small">
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Action</th>
      </tr>
      {% for category in categoryBooks %}
      <tr>
        <td>{{ category.name }}</td>
        <td>{{ category.description }}</td>
        <td>
          <button><a href="{% url 'book:categoryFormUpdate' category.id %}">Sửa</a></button>
          <button><a href="{% url 'book:categoryFormDelete' category.id %}">Xóa</a></button>
        </td>
      </tr>
      {% endfor %}
    </table>


    <h2>Publisher Table</h2>

    <button><a href="{% url 'book:publisherForm' %}">Create new publisher</a></button>
    <table class="w3-table-all w3-small">
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Action</th>
      </tr>
      {% for publisher in publishers %}
      <tr>
        <td>{{ publisher.name }}</td>
        <td>{{ publisher.address }}</td>
        <td>
          <button><a href="{% url 'book:publisherFormUpdate' publisher.id %}">Sửa</a></button>
          <button><a href="{% url 'book:publisherFormDelete' publisher.id %}">Xóa</a></button>
        </td>
      </tr>
      {% endfor %}
    </table>


    <h2>Book Table</h2>

    <button><a href="{% url 'book:bookForm' %}">Create new book</a></button>
    <table class="w3-table-all w3-small">
      <tr>
        <th>ISBN</th>
        <th>title</th>
        <th>summary</th>
        <th>numberOfPages</th>
        <th>language</th>
        <th>image</th>
        <th>author</th>
        <th>categoryBook</th>
        <th>publisher</th>
      </tr>
      {% for book in books %}
      <tr>
        <td>{{ book.ISBN }}</td>
        <td>{{ book.title }}</td>
        <td>{{ book.summary }}</td>
        <td>{{ book.numberOfPages }}</td>
        <td>{{ book.language }}</td>
        <td>{{ book.image }}</td>
        <td>{{ book.author }}</td>
        <td>{{ book.categoryBook }}</td>
        <td>{{ book.publisher }}</td>
        <td>
          <button><a href="{% url 'book:bookFormUpdate' book.ISBN %}">Sửa</a></button>
          <button><a href="{% url 'book:bookFormDelete' book.ISBN %}">Xóa</a></button>
        </td>
      </tr>
      {% endfor %}
    </table>


    <h2>BookItem Table</h2>

    <button><a href="{% url 'book:bookItemForm' %}">Create new bookItem</a></button>
    <table class="w3-table-all w3-small">
      <tr>
        <th>barcode</th>
        <th>book name</th>
        <th>price</th>
        <th>discount</th>
        <th>inventory</th>
      </tr>
      {% for bookItem in bookItems %}
      <tr>
        <td>{{ bookItem.barcode }}</td>
        <td>{{ bookItem.book.title }}</td>
        <td>{{ bookItem.price }}</td>
        <td>{{ bookItem.discount }}</td>
        <td>{{ bookItem.inventory }}</td>
        <td>
          <button><a href="{% url 'book:bookItemFormUpdate' bookItem.barcode %}">Sửa</a></button>
          <button><a href="{% url 'book:bookItemFormDelete' bookItem.barcode %}">Xóa</a></button>
        </td>
      </tr>
      {% endfor %}
    </table>

  </div>

  <!-- End page content -->
</div>
{% endblock %}

book/templates/book/delete.html
{% extends 'home/base.html' %}
{% block content %}
    <!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:250px">

  <!-- Push down content on small screens -->
  <div class="w3-hide-large" style="margin-top:83px"></div>

  <!-- Top header -->
  <header class="w3-container w3-xlarge">
    <p class="w3-left">BOOK CONTROLLER</p>
    <p class="w3-right">
      <i class="fa fa-shopping-cart w3-margin-right"></i>
      <i class="fa fa-search"></i>
    </p>
  </header>

  <!-- Product grid -->
  <div class="w3-row w3-grayscale">
    <h2>Authors Form</h2>
    <p>Bạn thực sự muốn xóa {{ item.name }}</p>
    <form action="" method="post">
      {% csrf_token %}
      <p><a href="{% url 'book:bookController' %}">cancer</a></p>
      <button type="submit">Xác nhận</button>
    </form>
  </div>

  <!-- End page content -->
</div>
{% endblock %}